### ISSUE TITLE
Error downloading gEvent package after docker compose up

### ISSUE THREAD

**Issue by guoguojiacheng** [open-telemetry/opentelemetry-demo-webstore#127]
# Question

Use [Github Discussions](https://github.com/open-telemetry/opentelemetry-demo-webstore/discussions/).
#0 53.03 Collecting gevent>=20.9.0
#0 53.87   Downloading gevent-21.12.0-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (6.1 MB)
#0 73.15      ━━━━━                                    0.8/6.1 MB 189.8 kB/s eta 0:00:28
#0 73.16 ERROR: Exception:
#0 73.16 Traceback (most recent call last):
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
#0 73.16     yield
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 519, in read
#0 73.16     data = self._fp.read(amt) if not fp_closed else b""
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
#0 73.16     data = self.__fp.read(amt)
#0 73.16   File "/usr/local/lib/python3.10/http/client.py", line 465, in read
#0 73.16     s = self.fp.read(amt)
#0 73.16   File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
#0 73.16     return self._sock.recv_into(b)
#0 73.16   File "/usr/local/lib/python3.10/ssl.py", line 1274, in recv_into
#0 73.16     return self.read(nbytes, buffer)
#0 73.16   File "/usr/local/lib/python3.10/ssl.py", line 1130, in read
#0 73.16     return self._sslobj.read(len, buffer)
#0 73.16 TimeoutError: The read operation timed out
#0 73.16 
#0 73.16 During handling of the above exception, another exception occurred:
#0 73.16 
#0 73.16 Traceback (most recent call last):
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
#0 73.16     status = run_func(*args)
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
#0 73.16     return func(self, options, args)
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 339, in run
#0 73.16     requirement_set = resolver.resolve(
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
#0 73.16     result = self._result = resolver.resolve(
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
#0 73.16     state = resolution.resolve(requirements, max_rounds=max_rounds)
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
#0 73.16     failure_causes = self._attempt_to_pin_criterion(name)
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
#0 73.16     criteria = self._get_updated_criteria(candidate)
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 204, in _get_updated_criteria
#0 73.16     self._add_to_criteria(criteria, requirement, parent=candidate)
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
#0 73.16     if not criterion.candidates:
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
#0 73.16     return bool(self._sequence)
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
#0 73.16     return any(self)
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
#0 73.16     return (c for c in iterator if id(c) not in self._incompatible_ids)
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
#0 73.16     candidate = func()
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 215, in _make_candidate_from_link
#0 73.16     self._link_candidate_cache[link] = LinkCandidate(
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 288, in __init__
#0 73.16     super().__init__(
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
#0 73.16     self.dist = self._prepare()
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
#0 73.16     dist = self._prepare_distribution()
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 299, in _prepare_distribution
#0 73.16     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 487, in prepare_linked_requirement
#0 73.16     return self._prepare_linked_requirement(req, parallel_builds)
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 532, in _prepare_linked_requirement
#0 73.16     local_file = unpack_url(
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 214, in unpack_url
#0 73.16     file = get_http_url(
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 94, in get_http_url
#0 73.16     from_path, content_type = download(link, temp_dir.path)
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_internal/network/download.py", line 146, in __call__
#0 73.16     for chunk in chunks:
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 304, in _rich_progress_bar
#0 73.16     for chunk in iterable:
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
#0 73.16     for chunk in response.raw.stream(
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 576, in stream
#0 73.16     data = self.read(amt=amt, decode_content=decode_content)
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 512, in read
#0 73.16     with self._error_catcher():
#0 73.16   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
#0 73.16     self.gen.throw(typ, value, traceback)
#0 73.16   File "/usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
#0 73.16     raise ReadTimeoutError(self._pool, None, "Read timed out.")
#0 73.16 pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
#0 82.54 WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
#0 82.54 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
------
failed to solve: executor failed running [/bin/sh -c pip install --prefix="/usr/local/" -r ./requirements.txt]: exit code: 2

**Comment by fatsheep9146** [comment]
I think this maybe you machine can't connect to ```files.pythonhosted.org``` according to the error message. I think you can check with ```curl files.pythonhosted.org``` on your machine directly.

**Comment by guoguojiacheng** [comment]
> I think this maybe you machine can't connect to `files.pythonhosted.org` according to the error message. I think you can check with `curl files.pythonhosted.org` on your machine directly.

Thank you very much. I have replaced the source of PIP and it works normally
