### ISSUE TITLE
release a alpha/beta version to trigger the image build/push

### ISSUE THREAD

**Issue by wph95** [open-telemetry/opentelemetry-demo-webstore#135]
#41 need demo-webstore docker image

**Comment by austinlparker** [comment]
See https://github.com/open-telemetry/opentelemetry-demo-webstore/actions/runs/2502937267

**Comment by wph95** [comment]
Thx @austinlparker It's work! https://github.com/open-telemetry/opentelemetry-demo-webstore/pkgs/container/demo

**Comment by wph95** [comment]
@austinlparker could you create a new version release? 
because we merge https://github.com/open-telemetry/opentelemetry-demo-webstore/pull/184

**Comment by austinlparker** [comment]
v0.2.0 has been cut

**Comment by austinlparker** [comment]
Re-ran the build and this is working now! Thanks! 🎉
