### ISSUE TITLE
Copy opentelemetry-microservices-demo to opentelemetry-demo-webstore

### ISSUE THREAD

**Issue by julianocosta89** [open-telemetry/opentelemetry-demo-webstore#14]
This has been discussed during the [OpenTelemetry Demo Application SIG Meeting](https://docs.google.com/document/d/16f-JOjKzLgWxULRxY8TmpM_FjlI1sthvKurnqFz9x98/edit#heading=h.b9liq2yzxczd).

Here are the steps that we will be following:

- [x] Create branch `online-boutique`
- [x] Copy the code as-is from [opentelemetry-microservices-demo](https://github.com/julianocosta89/opentelemetry-microservices-demo)
- [x] Make minimum changes to clean up unnecessary parts (istio, cloudbuild and some docs)
- [x] Update changelog
- [x] Merge branch into main
- [x] Delete branch `online-boutique`

FYI: @open-telemetry/demo-webstore-maintainers

**Comment by reyang** [comment]
Thanks @julianocosta89!

Here are the additional items we need to consider:

1. Confirm with the original author(s) regarding licensing / copyright.
2. Check if there are licensing / copyright issues related to dependencies / submodules / etc.
3. Decide how much history / changelog are we going to keep.
4. Do we need to preserve the commit history from the original source? (I _guess_ the answer is no - by looking at other donations to OpenTelemetry).

**Comment by cartersocha** [comment]
@mtwo, @jsuereth, can you provide guidance on the licensing / copyright changes we should be making. I think our preference is for the copyright owners to be OpenTelemetry itself right, @reyang?

**Comment by mtwo** [comment]
I think so (?), though I'm not an expert at this. @lizthegrey and possibly @tedsuo know way more about this than I do.

**Comment by reyang** [comment]
OpenTelemetry community would prefer the copyright to be "OpenTelemetry Authors" - https://github.com/open-telemetry/community/blob/4b53b7ffb6390e57850e9a916bd63253349a7770/CONTRIBUTING.md#copyright-notices. But this has to be blessed by the previous author(s) (I think they have the ultimate saying, unless it's documented in a different way).

Here goes an example - I worked with .NET Foundation and the ASP.NET team to get their bless on https://github.com/open-telemetry/opentelemetry-dotnet/pull/2225.

There are different examples - e.g. .NET auto-instrumentation https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/src/OpenTelemetry.AutoInstrumentation.Native/lib/fmt_x64-windows-static/share/fmt/copyright.

**Comment by lizthegrey** [comment]
What @reyang said.

**Comment by reyang** [comment]
Here goes a summary of existing copyright info (by scanning through the temporary `online-boutique` branch):

**Copyright `<year>` the original author or authors.**
https://github.com/open-telemetry/opentelemetry-demo-webstore/blob/b9b5998270877d92e56e69883028c278d0d2d85f/src/adservice/gradlew.bat#L2

**Copyright © `<year>` the original authors.**
https://github.com/open-telemetry/opentelemetry-demo-webstore/blob/b9b5998270877d92e56e69883028c278d0d2d85f/src/adservice/gradlew#L4

**Copyright `<year>` The gRPC Authors**
https://github.com/open-telemetry/opentelemetry-demo-webstore/blob/b9b5998270877d92e56e69883028c278d0d2d85f/pb/grpc/health/v1/health.proto#L1

**Copyright `<year>` Google LLC**
https://github.com/open-telemetry/opentelemetry-demo-webstore/blob/b9b5998270877d92e56e69883028c278d0d2d85f/cloudbuild.yaml#L1

**Comment by lizthegrey** [comment]
In this case, since it's forking a long-established project, I think we credit OpenTelemetry Authors for any significant modifications, but we leave the existing copyrights alone.

**Comment by reyang** [comment]
Based on my [investigation](https://github.com/open-telemetry/opentelemetry-demo-webstore/issues/14#issuecomment-1124612696), it seems everything in the current `online-boutique` branch should be compatible with `Apache License, Version 2.0` (disclaimer: I'm not an attorney).

The copyright information shouldn't be a blocker if we follow what @lizthegrey [suggested](https://github.com/open-telemetry/opentelemetry-demo-webstore/issues/14#issuecomment-1124614660).

**Comment by cartersocha** [comment]
Great thanks for the help. @julianocosta89 we should be okay from a licensing perspective. We'll follow Liz's guidance

**Comment by cartersocha** [comment]
@julianocosta89 I think steps 3 & 4 are now done. Please review then complete the merge if possible

**Comment by cartersocha** [comment]
Just merged the pr into main & deleted the branch. Closing this issue.
