### ISSUE TITLE
getting connection refused with Cart Service 

### ISSUE THREAD

**Issue by puckpuck** [open-telemetry/opentelemetry-demo-webstore#140]
# Bug Report

Which version of the demo you are using? 
[982cefedaa504a52b658e32d45e4d5f5a8ca68bd](https://github.com/open-telemetry/opentelemetry-demo-webstore/commits/982cefedaa504a52b658e32d45e4d5f5a8ca68bd) - PR #105 

## Symptom

The cart service seems to be unreachable, and all upstream services return an error when attempting to connect

**What is the expected behavior?**

No errors

**What is the actual behavior?**

Getting this error:
`transport: Error while dialing dial tcp 172.18.0.11:7070: connect: connection refused`

## Reproduce

```
git checkout 982cefedaa504a52b658e32d45e4d5f5a8ca68bd
docker compose build
docker compose up
```

look at any of the traces for /cart/checkout on the frontend service in Jaeger

We will close this issue if:

* The steps you provided are complex.
* If we can not reproduce the behavior you're reporting.

## Additional Context

See image of broken trace
![Screen Shot 2022-06-15 at 12 33 02 AM](https://user-images.githubusercontent.com/1296118/173737931-724ea544-10b6-4c8f-b6c9-00ce6514a811.png)

**Comment by julianocosta89** [comment]
@puckpuck can we revert the PR #105 in order to have a running sample again?

**Comment by robbkidd** [comment]
My current workaround for this is to add the following to the cartservice environment stanza in docker-compose.yml:

```
- ASPNETCORE_URLS=http://*:${CART_SERVICE_PORT}
```

This gets me past the frontend service failing to connect to cartservice and to a new error, a 500 from cartservice itself:

```
The request matched multiple endpoints. Matches: 

gRPC - Unimplemented service
gRPC - Unimplemented service
```

**Comment by puckpuck** [comment]
> @puckpuck can we revert the PR #105 in order to have a running sample again?

I'm going to investigate this deeper to try and figure out what in the PR broke it. I'll know more by tomorrow.

**Comment by mic-max** [comment]
> > @puckpuck can we revert the PR #105 in order to have a running sample again?
> 
> I'm going to investigate this deeper to try and figure out what in the PR broke it. I'll know more by tomorrow.

Ya I'd like to know why as well. I wanted to remove the generate files, which `./services/CartService.cs` is one of, but obviously would prefer the example still works :D

**Comment by puckpuck** [comment]
> Ya I'd like to know why as well. I wanted to remove the generate files, which `./services/CartService.cs` is one of, but obviously would prefer the example still works :D

Though the logic doesn't seem like much, I don't believe that file is generated. It acts as a thin wrapper around calling into the CartStore itself.

**Comment by mic-max** [comment]
> > Ya I'd like to know why as well. I wanted to remove the generate files, which `./services/CartService.cs` is one of, but obviously would prefer the example still works :D
> 
> Though the logic doesn't seem like much, I don't believe that file is generated. It acts as a thin wrapper around calling into the CartStore itself.

Ah that does seem plausible. I wonder if this wrapper pattern is typically used in C# protobuf projects..
