### ISSUE TITLE
docker image ghcr.io/open-telemetry/demo is private, expect it to be public 

### ISSUE THREAD

**Issue by wph95** [open-telemetry/opentelemetry-demo-webstore#156]
this image repo is private 
https://github.com/open-telemetry/opentelemetry-demo-webstore/pkgs/container/demo

need someone to set it to public

**Comment by cartersocha** [comment]
@austinlparker was this set during that release we had a couple days ago?

**Comment by austinlparker** [comment]
I didn't set anything to do with it; Who manages that container registry account?

**Comment by JaredTan95** [comment]
from github packages docs : https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility

Do we need the org owners or who have admin permissions to open it?

**Comment by JaredTan95** [comment]
from github packages docs : https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility

Do we need the org owners or who have admin permissions to open it?

**Comment by reyang** [comment]
It seems I've figured out how to do that, would you confirm if the package is now public / meeting your expectations? I'll follow up regarding whether we should/can give the permission to repo maintainers.

**Comment by JaredTan95** [comment]
> It seems I've figured out how to do that, would you confirm if the package is now public / meeting your expectations? I'll follow up regarding whether we should/can give the permission to repo maintainers.

Great works. the package is now public:
```bash
$ docker pull ghcr.io/open-telemetry/demo:v0.2.0-alpha-currencyservice
v0.2.0-alpha-currencyservice: Pulling from open-telemetry/demo
2408cc74d12b: Pull complete
5b80453a567d: Pull complete
3420de6432e1: Pull complete
65b549a28248: Pull complete
69b4d7dea9e1: Pull complete
ee73b67bb367: Pull complete
2558ca69ea3f: Pull complete
31d29db41095: Pull complete
Digest: sha256:807f04e0e22a530fdfaf286b936f064d43db36504175d0bba0e57ffb76179844
Status: Downloaded newer image for ghcr.io/open-telemetry/demo:v0.2.0-alpha-currencyservice
ghcr.io/open-telemetry/demo:v0.2.0-alpha-currencyservice
```
