### ISSUE TITLE
Do we need Discussions?

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-demo-webstore#3]
We have it in the spec repo and many other languages SIGs.

e.g. https://github.com/open-telemetry/opentelemetry-specification/discussions

**Comment by cartersocha** [comment]
I think it would be valuable.

**Comment by cartersocha** [comment]
@mtwo I don't have the ability to enable discussions. Do you or @tigrannajaryan have access?

**Comment by tigrannajaryan** [comment]
Enabled. You should be able to edit the first discussion: https://github.com/open-telemetry/opentelemetry-demo-webstore/discussions/9
