### ISSUE TITLE
Reimplement 'shippingservice' in Rust

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-demo-webstore#35]
**Objective**

Re-implement the 'shippingservice' in Rust.

This should be a drop-in replacement.

**Comment by GaryPWhite** [comment]
@cartersocha I cannot assign myself, please feel free to assign me :)

**Comment by TommyCpp** [comment]
Please feel free to let me know if you need any help :)

**Comment by GaryPWhite** [comment]
@TommyCpp I'll tag you in the PR when it's ready for some review, specifically I'm open to learning about better practices for OTel as I implement it :)
