### ISSUE TITLE
Reimplement 'emailservice' in Ruby

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-demo-webstore#37]
**Objective**

Re-write the emailservice to Ruby.

This should be a drop-in replacement.

**Comment by cartersocha** [comment]
@ahayworth fyi

**Comment by ahayworth** [comment]
@cartersocha Sorry - this was buried in my notifications. I think we can keep it here, I'll just put it on the agenda for the SIG next week.
