### ISSUE TITLE
Review and enhance tracing support for ad service service (Java)

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/opentelemetry-demo-webstore#60]
The following is a list of requirements that we need to evaluate before declaring v1 for trace telemetry. These requirements are across the entire application; Not all services will meet all requirements. Determine the relevant features for this service. 

- [x] Automatic Instrumentation is being used where appropriate.
- [ ] Library instrumentation is being used if automatic instrumentation is unavailable.
- [ ] #151
  - [x] #152
  - [ ] New spans are being created from existing spans.
- [ ] Automatic and Manual Context Propagation are being demonstrated.
  - [ ] Interprocess context propagation is demonstrated.
- [ ] Telemetry is not being sampled upfront.
- [ ] Telemetry is not being filtered upfront.
- [ ] Baggage is being set and read appropriately (i.e., baggage must be explicitly set as attributes on spans)

Referencing: https://github.com/open-telemetry/opentelemetry-demo-webstore/issues/42

Service: https://github.com/open-telemetry/opentelemetry-demo-webstore/blob/main/src/adservice/README.md

**Comment by puckpuck** [comment]
Should we check this one as well for Java?

- [ ] Library instrumentation is being used if automatic instrumentation is unavailable.

**Comment by julianocosta89** [comment]
@puckpuck we could maybe add a Feature Flag to decide if the Jave OTel Agent will or not be deployed to the AdService.
And when not, then the library instrumentation should be there.
