### ISSUE TITLE
Setup CI workflow to Docker Hub

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/opentelemetry-demo-webstore#78]
The most recent build of the community demo should be available for download on Docker Hub & have automated deployment from the repo. 

The community demo should be posted by the community "[otel](https://hub.docker.com/u/otel)" user on the docker hub. 

 

- [x] Define image_name image_tag format
- [x]  Setup CI workflow to build the image
- [x]  Setup CI workflow to push image to GitHub package (via GitHub action)
- [ ]  docker hub credentials
- [ ]  push image to docker hub (via GitHub action)

**Comment by wph95** [comment]
I am interested in helping to complete this issue.
I've done some research 
https://github.com/open-telemetry/community/issues/573
Probably using the GitHub package is a better option for now, I see other sigs are using the GitHub package.
https://github.com/orgs/open-telemetry/packages

**Comment by cartersocha** [comment]
We’d love the help! 

We still need to finalize whether we’re using the OTel community account or a separate account to prevent image spam. But outside of exact account credentials this item is ready to be worked in

@tigrannajaryan, do you have a preference on where we post the images? @julianocosta89 & I are concerned adding 10 images to the community account might be a bit spammy

**Comment by wph95** [comment]
>  I am concerned adding 10 images to the community account might be a bit spammy

Yeah, I'm worried about that too

Some possible ways to solve the problem

1. used different docker tag 

   ```
   otel/demo:1.0.0b1-adservice
   otel/demo:1.0.0b1-checkoutservice
   otel/demo:latest-checkoutservice
   ```

2. All-in-one docker image(like jaeger). used a script/CLI/makefile to run the microservices 

   ```
   docker run --rm -d otel/demo:1.0.0b1 adservice
   docker run --rm -d otel/demo:1.0.0b1 checkoutservice
   ```

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan, do you have a preference on where we post the images? @julianocosta89 & I are concerned adding 10 images to the community account might be a bit spammy

I agree if it is 10 images then it is not very desirable. Can we do all-in-one like @wph95 suggests?

If all-in-one is not an option github packages seems like a good approach.

**Comment by cartersocha** [comment]
Let’s try the all in one approach then. @wph95 let us know if you’re running into any blockers / when you need the credentials 

Let’s see if we can use cache_from to reduce build time too like @aabmass suggested on slack

**Comment by wph95** [comment]
Some progress

1. all-in-one is more complex and involves changing the dockerfile for almost all services, because our services have different runtimes. Unlike jaeger, we only need to add some binary.
   Personally, I don't think it's a good choice for now.

Some options

1. `ghcr.io/open-telemetry/demo-{SERVICE_NAME}:{VERSION}`  

   > `ghcr.io/open-telemetry/demo-adservice:0.1.0`

   Good

   - image name is simple

   - don't need extra credentials if use github action to push image 

   Bad

   - need create 10 image

2. ` ghcr.io/open-telemetry/demo:{VERSION}-{SERVICE_NAME}`

   >  `ghcr.io/open-telemetry/demo:0.1.0-adservice`

   Good

   - only need create 1 image
   - don't need extra credentials if use github action to push image 

   Bad

   - image name a little strange 

3. `otel/demo-{SERVICE_NAME}:{VERSION}`

   > .`otel/demo-adservice:0.1.0`

   Good

   - image name is simple

   Bad

   - need create 10 image
   - need dockerhub credentials/token

4. `otel/demo:{VERSION}-{SERVICE_NAME}` 

   > `otel/demo:0.1.0-adservice`

   Good 

   - More like the official image
   - 1 image

   Bad

   - need dockerhub credentials/token

**Comment by cartersocha** [comment]
I’d lean option 3 or maybe 4. I don’t see docker credentials as a big blocker or negative so we should be good there. We should align with what the other community projects are doing too & it seems docker hub is the approach. 

Why / how does changing the service / version determine 1 image vs. 10?

**Comment by cartersocha** [comment]
& if we’re producing 10 images we should just create a OTel-demo user. So the naming would update to something like otel-demo/{version}—{service}

**Comment by wph95** [comment]
by the way, using the dockerhub/ github package is not a matter of either/or. We can save in both places.
e.g.
https://hub.docker.com/r/otel/opentelemetry-collector-contrib/tags
https://github.com/open-telemetry/opentelemetry-collector-releases/pkgs/container/opentelemetry-collector-releases%2Fopentelemetry-collector-contrib

**Comment by cartersocha** [comment]
@wph95 what's the difference in scenarios 3 & 4 that causes 10 images to be reduced to 1?

**Comment by wph95** [comment]
> @wph95 what's the difference in scenarios 3 & 4 that causes 10 images to be reduced to 1?

sorry , I used wrong word. I updated the scenario
10 images repository to 1 image repository

---
It is not very uncommon for us to encounter situations. For example, we can refer to the docker official python image https://hub.docker.com/_/python
They have encountered similar problems. They solved it by adding the information to the image version.

```
python:<version
python:<version>-slim
python:<version>-alpine
```

**Comment by wph95** [comment]
So I think we need to address that for now. (it's blocking me to finish this issue )
It's the choice of
` otel/demo-{SERVICE_NAME}:{VERSION}`.
or 
` otel/demo:{VERSION}-{SERVICE_NAME}`.

- [ ] Define image_name image_tag format 
- [x] Build the image (via github action)
- [x] push image to github package (via github action)
- [ ] dockerhub credentials

**Comment by cartersocha** [comment]
ahh that makes sense! Thanks for the context. 

I like the idea of the version then service name to consolidate in one repository personally. @julianocosta89 any preferences?

@tigrannajaryan, I think we’ll create a dedicated demo account. I’m assuming we still want this controlled by the community overall. How would you like this set up?

**Comment by cartersocha** [comment]
@mic-max do you have an opinion on image naming conventions?

**Comment by mic-max** [comment]
> @mic-max do you have an opinion on image naming conventions?

`otel/demo-{SERVICE_NAME}:{VERSION}` seems more natural to me, I don't have a strong preference since I am not too knowledgeable about Docker development

One thing to consider though is how the versions will work with each other / compatibility. When one image relies on another it will it also need to specify the version? How will the version numbers be increased with changes, if it only affects one image do we only do a release for that image and update it's version number alone or do we update all the images version even though 9/10 of them don't have any real changes to them.

**Comment by cartersocha** [comment]
For single service updates they shouldn’t affect the versions of other images in my opinion. You would default to the latest version of each service in which case it probably makes sense to start with services stored individually

**Comment by julianocosta89** [comment]
Hello all, sorry I've missed this thread.

I personally thing that `otel/demo-{SERVICE_NAME}:{VERSION}` is more natural, but that would push the 10+ images to the OTel registry,  what we don't want, so I'm good in going forward with the following one:
`otel/demo:{VERSION}-{SERVICE_NAME}`

Thx @wph95 for taking care of that.

**Comment by cartersocha** [comment]
@julianocosta89 i think wed just create a new account. Also we'll need to include language in the image name. 

One service can have multiple implementations in our architecture. Its supposed to be modular. 

Whatever order we choose we need service, language, version.

**Comment by cartersocha** [comment]
But splitting by service makes the most sense conceptually to me

**Comment by cartersocha** [comment]
To circle back on this during the SIG meeting we determined we are not planning on supporting multiple languages of individual services for v1. We might still want to keep that in the naming convention for future additions but we can revert to service / version name only if we want. 

@wph95 feel free to make a proposal for which setup you'd like

**Comment by cartersocha** [comment]
@mic-max, @wph95, @julianocosta89 lets get this closed. 

Sounds like were down to 2 options;
1. Name the images version-service-language under the OTel community account. 
this would be stored as a single docker hub image but would be differentiated inside that repo by service name. 
2. Name the images service-language-version. Store them separately as 10 images on docker hub in a newly created OTel-demo account. 

If storing under a singular image doesnt affect the docker compose

**Comment by mic-max** [comment]
> `otel/demo:{VERSION}-{SERVICE_NAME}`

I'm fine with this approach 👍

**Comment by austinlparker** [comment]
I've opened a request to have the opentelemetrybot credentials added to this repository in order to publish images there. See https://github.com/open-telemetry/community/issues/1073

**Comment by austinlparker** [comment]
As for naming, I don't see the problem in doing `otel/demo-{SERVICE_NAME}:{VERSION}`. not like container images are an exhaustible resource? but if there's no harm in doing `otel/demo:{VERSION}-{SERVICE_NAME}` from a container-y point of view then that's fine.

**Comment by cartersocha** [comment]
The issue is adding too many images to the otel repo by following service - version name. We're effectively doubling the amount of containers tied to the user which isn't ideal from a community impact perspective. 

Sounds like version-service is the probable choice

**Comment by cartersocha** [comment]
@austinlparker thanks for opening the issue. From the maintainers slack it sounds like we just need to wait for some to take a look or does it need to be formally assigned?

**Comment by wph95** [comment]
@cartersocha 
I plan to finish #91, as the first version
1. build image by  GitHub action
2. push the image to GitHub package with format `ghcr.io/open-telemetry/demo:{VERSION}-{SERVICE_NAME}`

After our GitHub action has the secrect for the dockerhub  `otel` org token, I will create pr and have the GitHub action push image to docker hub

**Comment by austinlparker** [comment]
> @austinlparker thanks for opening the issue. From the maintainers slack it sounds like we just need to wait for some to take a look or does it need to be formally assigned?

I believe someone will come along and pick it up, but maybe poke somebody if there's no traction in a couple days

**Comment by wph95** [comment]
reopen it, until we finished pushing the image to dockerhub then close it.

**Comment by tigrannajaryan** [comment]
Hey folks, sorry it took so long, we had to re-create a bot account on Docker hub. It is ready now. Tell where you need the credentials and I will enter them.

**Comment by wph95** [comment]
@tigrannajaryan 
thx your help. I expect to have `DOCKER_USERNAME ` and `DOCKER_PASSWORD ` in our github action secrets

ref
https://docs.github.com/en/actions/security-guides/encrypted-secrets

https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan thx your help. I expect to have `DOCKER_USERNAME ` and `DOCKER_PASSWORD ` in our github action secrets
> 
> ref https://docs.github.com/en/actions/security-guides/encrypted-secrets
> 
> https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub

I missed this notification somehow. If this happens again please ping me on Slack.

DOCKER_USERNAME and DOCKER_PASSWORD secrets now added to this repo. You should be able to push. The secret as "Read & Write" Docker hub premission.
