### ISSUE TITLE
README.md has an invalid link [/docs/development-principles.md]

### ISSUE THREAD

**Issue by wph95** [open-telemetry/opentelemetry-demo-webstore#85]
README.md
> See the [Development Principles](/docs/development-principles.md) doc for more information.

our repo no /docs/development-principles.md

https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/docs/development-principles.md

**Comment by cartersocha** [comment]
ty for raising the issue

https://github.com/open-telemetry/opentelemetry-demo-webstore/pull/86
