### ISSUE TITLE
Is there any plan to add demonstration of the Java technology stack?

### ISSUE THREAD

**Issue by JaredTan95** [open-telemetry/opentelemetry-demo-webstore#87]
# Question
Hi, 
I've given a rough preview of the technology stack used in the `webstore` demo, and I noticed the grpc framework is involved.
But, from my point of view, the content of the Java technology stack involves less, especially the more popular springboot/springcloud.

Do we have a plan on this?

BTW, I can participate in this part of the enhancement. :-P

Use [Github Discussions](https://github.com/open-telemetry/opentelemetry-demo-webstore/discussions/).

**Comment by cartersocha** [comment]
The thought with gRPC & http as our communication protocols is that they’d be broadly generic to cover any service communication. 

I’d recommend commenting or adding this suggestion to our open architectural doc. There’s a link in GitHub discussions to it. 

I’m not sure of any Java specific additions outside of ensuring all the OpenTelemetry signals / features are demonstrated. But we’d certainly love some energy in this space

**Comment by JaredTan95** [comment]
> 

Okay, I will add it.
